source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail' ),
    path('change/' , UserChangeView.as_view(), name='user_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import AdsList , AdDetail , AdsCreate , AdsUpdate,AdsDelete ,  CommentsCreate , CommentDelete , ListMooderateComments , ModerYesView ,ModerNoView

app_name = 'webapp'

urlpatterns = [
    path('', AdsList.as_view() , name='index'),
    path('ad_detail/<int:pk>/', AdDetail.as_view(), name='ad_detail'),
    path('adds/add/', AdsCreate.as_view(), name='ad_create'),
    path('adds/<int:pk>/update/', AdsUpdate.as_view(), name='ad_update'),
    path('adds/<int:pk>/delete/', AdsDelete.as_view(), name='ad_delete'),
    path('adds/<int:pk>/comments_add/', CommentsCreate.as_view(), name='comments_create'),
    path('adds/<int:pk>/comments_delete/', CommentDelete.as_view(), name='comments_delete'),
    path('adds/moderation/', ListMooderateComments.as_view(), name='ad_moder_list'),
    path('adds/<int:pk>/moderation/yes/', ModerYesView.as_view(), name='moder_choose_yes'),
    path('adds/<int:pk>/moderation/no/', ModerNoView.as_view(), name='moder_choose_no'),
]

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    git_profile = models.URLField(max_length=200,null=True, blank=True, verbose_name='Ссылка на github')
    about_user = models.TextField(max_length=2000,null=True, blank=True, verbose_name='О себе')
    phone = models.CharField(max_length=13, null=True, blank=True, verbose_name='Телефон')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [
            ('can_see_users', 'Может просматривать пользователей')
        ]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
STATUS_CHOICES = [('for_moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('for_delete', 'На удаление')]
# Create your models here.


class Category(models.Model):
    categoryname = models.CharField(max_length=150, null=False, blank=False, verbose_name="Категория")

    def __str__(self):
        return f'{self.categoryname}'
class Ads(models.Model):
    picture = models.ImageField(null=True, blank=True, upload_to='picture', verbose_name='Картинка')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=2000, verbose_name='Описание', null=True, blank=True)
    ads_author = models.ForeignKey(get_user_model(), related_name='author' , on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('webapp.Category', related_name='category', on_delete=models.PROTECT, verbose_name="Категория")
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name='Цена')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0],
                                verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления')


    class Meta:
        permissions = [("view_not_moderated_ads", "Просмотр непромодерированных объявлений")]
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    ad = models.ForeignKey('webapp.Ads', related_name='comment', on_delete=models.CASCADE,
                                verbose_name='Комментарий')
    text = models.TextField(max_length=2000, verbose_name='Текст', null=False, blank=False)
    comment_author = models.ForeignKey(get_user_model(), related_name='comment_author', on_delete=models.CASCADE,
                               verbose_name='Автор', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

source/accounts/forms.py
import re
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from accounts.models import Profile
from django import forms


class MyUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2','first_name', 'last_name', 'email']
        field_classes = {'username': UsernameField}


    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if last_name or first_name:
            pass
        else:
            raise ValidationError('Fill out First name or Second name ')

class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar','git_profile','about_user', 'phone']

source/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import redirect
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from accounts.models import Profile
from django.contrib.auth import get_user_model
from django.views.generic.list import MultipleObjectMixin, ListView

class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ads = self.object.author.exclude(status='for_delete')
        if self.request.user != self.object:
            ads = ads.filter(status='published')
        context['ads'] = ads.order_by('-created_at')
        return context


class UserChangeView(PermissionRequiredMixin , UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'
    form_profile_class = ProfileChangeForm

    def has_permission(self):
        return self.get_object() == self.request.user

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(UserChangeView, self).get_context_data(**kwargs)
        if 'profile_form' not in kwargs:
            context['profile_form'] = self.form_profile_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.form_profile_class(instance=self.get_object().profile, data=request.POST,
                                               files=request.FILES)
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.get_object().pk})

class UserPasswordChangeView(PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.request.user.pk})

source/accounts/templates/user_change.html
{% extends 'base.html' %}


{% block title %}Profile change{% endblock %}

{% block content %}

    <h1>Поменять личные данные</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with fields_only=True %}
    {% include 'partial/form.html' with  form=profile_form button_text="Change" %}
</form>


{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}


{% block title %}Registration{% endblock %}

{% block content %}

    <h1>Регистрация</h1>
<form action="" method="post">
    {% include 'partial/form.html' with  button_text="register" %}
</form>


{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Пользователь{% endblock %}
{% block nav %}
    {% if user_obj.pk == request.user.pk %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:user_change' %}">Редактировать</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:password_change' %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
<div class="card mb-3" >
  <div class="row g-0">
  {% if user_obj.profile.avatar %}
    <div class="col-md-4">
      <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start" alt="...">
    </div>
  {% endif %}
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
        <p  class="card-text"><b>Имя:</b> {{ user_obj.first_name }}</p>
        <p class="card-text"><b>Фамилия:</b> {{ user_obj.last_name }}</p>
        <p class="card-text"><b>Почта:</b> {{ user_obj.email }}</p>
        <p class="card-text"><b>Гит:</b> {{ user_obj.profile.git_profile }}</p>
        <p class="card-text"><b>О себе:</b> {{ user_obj.profile.about_user }}</p>
        <p class="card-text"><b>Телефон:</b> {{ user_obj.profile.phone }}</p>
      </div>
    </div>
  </div>
</div>

{% for ad in ads %}
        <div class="card" style="width: 18rem;">
        {%  if ad.picture %}
            <img src="{{ ad.picture.url }}" class="card-img-top" alt="...">
        {% else %}
            <img src="{% static "images/empty.jpg" %}" class="card-img-top">
        {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ ad.title }}</h5>
              <p>{{ ad.price }}</p>
              <p>{{ad.get_status_display }}</p>
            <a href="{% url 'webapp:ad_detail' ad.pk %}" class="btn btn-primary">More...</a>
           {% if ad.ads_author == request.user %}
              {% if ad.status != 'rejected' %}
           <a href="{% url 'webapp:ad_update' ad.pk %}" class="btn btn-primary">Update</a>
              {% endif %}
          <a href="{% url 'webapp:ad_delete' ad.pk %}" class="btn btn-primary">Delete</a>
              {% endif %}
          </div>
        </div>
        </br>
    {% endfor %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}



{% block content %}

    <h1>Изменение пароля</h1>
<form action="" method="post">
    {% include 'partial/form.html' with  button_text="Change" %}
</form>


{% endblock %}