source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail' ),
    path('change/' , UserChangeView.as_view(), name='user_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import AdsList , AdDetail , AdsCreate , AdsUpdate,AdsDelete ,  CommentsCreate , CommentDelete , ListMooderateComments , ModerYesView ,ModerNoView

app_name = 'webapp'

urlpatterns = [
    path('', AdsList.as_view() , name='index'),
    path('ad_detail/<int:pk>/', AdDetail.as_view(), name='ad_detail'),
    path('adds/add/', AdsCreate.as_view(), name='ad_create'),
    path('adds/<int:pk>/update/', AdsUpdate.as_view(), name='ad_update'),
    path('adds/<int:pk>/delete/', AdsDelete.as_view(), name='ad_delete'),
    path('adds/<int:pk>/comments_add/', CommentsCreate.as_view(), name='comments_create'),
    path('adds/<int:pk>/comments_delete/', CommentDelete.as_view(), name='comments_delete'),
    path('adds/moderation/', ListMooderateComments.as_view(), name='ad_moder_list'),
    path('adds/<int:pk>/moderation/yes/', ModerYesView.as_view(), name='moder_choose_yes'),
    path('adds/<int:pk>/moderation/no/', ModerNoView.as_view(), name='moder_choose_no'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
STATUS_CHOICES = [('for_moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('for_delete', 'На удаление')]
# Create your models here.


class Category(models.Model):
    categoryname = models.CharField(max_length=150, null=False, blank=False, verbose_name="Категория")

    def __str__(self):
        return f'{self.categoryname}'
class Ads(models.Model):
    picture = models.ImageField(null=True, blank=True, upload_to='picture', verbose_name='Картинка')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=2000, verbose_name='Описание', null=True, blank=True)
    ads_author = models.ForeignKey(get_user_model(), related_name='author' , on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('webapp.Category', related_name='category', on_delete=models.PROTECT, verbose_name="Категория")
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name='Цена')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0],
                                verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления')


    class Meta:
        permissions = [("view_not_moderated_ads", "Просмотр непромодерированных объявлений")]
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    ad = models.ForeignKey('webapp.Ads', related_name='comment', on_delete=models.CASCADE,
                                verbose_name='Комментарий')
    text = models.TextField(max_length=2000, verbose_name='Текст', null=False, blank=False)
    comment_author = models.ForeignKey(get_user_model(), related_name='comment_author', on_delete=models.CASCADE,
                               verbose_name='Автор', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

source/webapp/forms.py
from django import forms
from webapp.models import Ads , Comment

class AdsForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ["title", "description", "category", "picture", "price"]



class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Ads
from webapp.forms import AdsForm , CommentsForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
class AdsList(ListView):
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    model = Ads
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(status='published').order_by('-created_at')

class AdDetail(DetailView):
    template_name = 'ads/ads_detail.html'
    context_object_name = 'ad'
    model = Ads

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment = self.object.comment.all()
        # if not self.request.user.has_perm('webapp.view_not_moderated_reviews'):
        #     reviews = reviews.filter(moderated=True)
        context['form'] = CommentsForm
        context['comments'] = comment.order_by('-created_at')
        return  context

class AdsCreate(LoginRequiredMixin, CreateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_create.html'

    def form_valid(self, form):
        author = self.request.user
        form.instance.ads_author = author
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsUpdate(PermissionRequiredMixin, UpdateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_update.html'

    def get(self, request, *args, **kwargs):
        ad =  get_object_or_404(Ads, pk = self.kwargs.get('pk'))
        if ad.status == 'rejected':
            raise PermissionDenied()
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.status = 'for_moderation'
        return super().form_valid(form)

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsDelete(PermissionRequiredMixin, DeleteView):
    model = Ads
    template_name = 'ads/ad_delete.html'
    permission_required = 'webapp.delete_review'
    context_object_name = 'ad'

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = 'for_delete'
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse('webapp:index')

class ListMooderateComments(PermissionRequiredMixin, ListView):
    model = Ads
    template_name = 'ads/moderate_list.html'
    context_object_name = 'ads'
    permission_required = 'webapp.view_not_moderated_ads'

    def get_queryset(self):
        return super().get_queryset().filter(status='for_moderation')

class ModerYesView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'published'
        ads.save()
        response = JsonResponse({})
        return response

class ModerNoView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'rejected'
        ads.save()
        response = JsonResponse({})
        return response

source/webapp/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView
from webapp.forms import CommentsForm
from webapp.models import Comment , Ads
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin



class CommentDelete(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk})

class CommentsCreate(CreateView):
    model = Comment
    form_class = CommentsForm

    def form_valid(self, form):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        form.instance.comment_author = self.request.user
        form.instance.ad = ad
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk} )

source/webapp/templates/partial/comment_form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{#{{ form.as_p }}#}
{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="form-error">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

{% if not fields_only %}
<p><input class="btn btn-dark" type="submit" value="{{ button_text }}"></p>
{% endif %}

source/webapp/templates/partial/comments.html
<h1>Комментарии</h1>
 {% for comment in comments %}
    <div class="card mt-2" style="width: 25rem;">
          <div class="card-body">
            <h5 class="card-title"><a href="{% url 'accounts:user_detail' comment.comment_author.pk %}">{{ comment.comment_author }}</a> {{ comment.comment_author.email }}</h5>
            <p>{{ comment.text }}</p>
              <h6>{{ comment.created_at }}</h6>

            <a href="{% url 'webapp:comments_delete' comment.pk %}" class="btn btn-primary">Delete</a>
          </div>
        </div>
    {% endfor %}

source/webapp/templates/partial/form.html
{% if not fields_only %}
{% csrf_token %}
{% endif %}

{#{{ form.as_p }}#}
{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="form-error">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

{% if not fields_only %}
<p><input class="btn btn-dark" type="submit" value="{{ button_text }}"></p>
{% endif %}

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>