source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail' ),
    path('change/' , UserChangeView.as_view(), name='user_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import AdsList , AdDetail , AdsCreate , AdsUpdate,AdsDelete ,  CommentsCreate , CommentDelete , ListMooderateComments , ModerYesView ,ModerNoView

app_name = 'webapp'

urlpatterns = [
    path('', AdsList.as_view() , name='index'),
    path('ad_detail/<int:pk>/', AdDetail.as_view(), name='ad_detail'),
    path('adds/add/', AdsCreate.as_view(), name='ad_create'),
    path('adds/<int:pk>/update/', AdsUpdate.as_view(), name='ad_update'),
    path('adds/<int:pk>/delete/', AdsDelete.as_view(), name='ad_delete'),
    path('adds/<int:pk>/comments_add/', CommentsCreate.as_view(), name='comments_create'),
    path('adds/<int:pk>/comments_delete/', CommentDelete.as_view(), name='comments_delete'),
    path('adds/moderation/', ListMooderateComments.as_view(), name='ad_moder_list'),
    path('adds/<int:pk>/moderation/yes/', ModerYesView.as_view(), name='moder_choose_yes'),
    path('adds/<int:pk>/moderation/no/', ModerNoView.as_view(), name='moder_choose_no'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
STATUS_CHOICES = [('for_moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('for_delete', 'На удаление')]
# Create your models here.


class Category(models.Model):
    categoryname = models.CharField(max_length=150, null=False, blank=False, verbose_name="Категория")

    def __str__(self):
        return f'{self.categoryname}'
class Ads(models.Model):
    picture = models.ImageField(null=True, blank=True, upload_to='picture', verbose_name='Картинка')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=2000, verbose_name='Описание', null=True, blank=True)
    ads_author = models.ForeignKey(get_user_model(), related_name='author' , on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('webapp.Category', related_name='category', on_delete=models.PROTECT, verbose_name="Категория")
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name='Цена')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0],
                                verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления')


    class Meta:
        permissions = [("view_not_moderated_ads", "Просмотр непромодерированных объявлений")]
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    ad = models.ForeignKey('webapp.Ads', related_name='comment', on_delete=models.CASCADE,
                                verbose_name='Комментарий')
    text = models.TextField(max_length=2000, verbose_name='Текст', null=False, blank=False)
    comment_author = models.ForeignKey(get_user_model(), related_name='comment_author', on_delete=models.CASCADE,
                               verbose_name='Автор', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

source/webapp/forms.py
from django import forms
from webapp.models import Ads , Comment

class AdsForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ["title", "description", "category", "picture", "price"]



class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Ads
from webapp.forms import AdsForm , CommentsForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
class AdsList(ListView):
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    model = Ads
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(status='published').order_by('-created_at')

class AdDetail(DetailView):
    template_name = 'ads/ads_detail.html'
    context_object_name = 'ad'
    model = Ads

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment = self.object.comment.all()
        # if not self.request.user.has_perm('webapp.view_not_moderated_reviews'):
        #     reviews = reviews.filter(moderated=True)
        context['form'] = CommentsForm
        context['comments'] = comment.order_by('-created_at')
        return  context

class AdsCreate(LoginRequiredMixin, CreateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_create.html'

    def form_valid(self, form):
        author = self.request.user
        form.instance.ads_author = author
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsUpdate(PermissionRequiredMixin, UpdateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_update.html'

    def get(self, request, *args, **kwargs):
        ad =  get_object_or_404(Ads, pk = self.kwargs.get('pk'))
        if ad.status == 'rejected':
            raise PermissionDenied()
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.status = 'for_moderation'
        return super().form_valid(form)

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsDelete(PermissionRequiredMixin, DeleteView):
    model = Ads
    template_name = 'ads/ad_delete.html'
    permission_required = 'webapp.delete_review'
    context_object_name = 'ad'

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = 'for_delete'
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse('webapp:index')

class ListMooderateComments(PermissionRequiredMixin, ListView):
    model = Ads
    template_name = 'ads/moderate_list.html'
    context_object_name = 'ads'
    permission_required = 'webapp.view_not_moderated_ads'

    def get_queryset(self):
        return super().get_queryset().filter(status='for_moderation')

class ModerYesView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'published'
        ads.save()
        response = JsonResponse({})
        return response

class ModerNoView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'rejected'
        ads.save()
        response = JsonResponse({})
        return response

source/webapp/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView
from webapp.forms import CommentsForm
from webapp.models import Comment , Ads
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin



class CommentDelete(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk})

class CommentsCreate(CreateView):
    model = Comment
    form_class = CommentsForm

    def form_valid(self, form):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        form.instance.comment_author = self.request.user
        form.instance.ad = ad
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk} )

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}List{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '../static/style.css' %}">
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Ads</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            {% block nav %}
            {% endblock %}
           {% if request.user.is_authenticated %}
          <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:ad_create' %}">Create Add+</a>
                </li>
              {% endif %}
          {% if request.user.is_authenticated %}
                 <li class="nav-item">
                <a class="nav-link" href="{%   url 'accounts:user_detail' request.user.pk %}">Hi, {{ request.user.username }}</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a>
                </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}">Login</a>
                </li>
              <li class="menu-right"><a href="{% url 'accounts:create' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{{ request.get_full_path }}{% endif %}" class="nav-link">Регистрация</a></li>
          {% endif %}
              {% if perms.webapp.view_not_moderated_ads %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:ad_moder_list' %}">Moderator List</a>
                </li>
              {% endif %}
          </ul>
 </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

</body>
</html>