source/accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail' ),
    path('change/' , UserChangeView.as_view(), name='user_change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')
]

source/main/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import AdsList , AdDetail , AdsCreate , AdsUpdate,AdsDelete ,  CommentsCreate , CommentDelete , ListMooderateComments , ModerYesView ,ModerNoView

app_name = 'webapp'

urlpatterns = [
    path('', AdsList.as_view() , name='index'),
    path('ad_detail/<int:pk>/', AdDetail.as_view(), name='ad_detail'),
    path('adds/add/', AdsCreate.as_view(), name='ad_create'),
    path('adds/<int:pk>/update/', AdsUpdate.as_view(), name='ad_update'),
    path('adds/<int:pk>/delete/', AdsDelete.as_view(), name='ad_delete'),
    path('adds/<int:pk>/comments_add/', CommentsCreate.as_view(), name='comments_create'),
    path('adds/<int:pk>/comments_delete/', CommentDelete.as_view(), name='comments_delete'),
    path('adds/moderation/', ListMooderateComments.as_view(), name='ad_moder_list'),
    path('adds/<int:pk>/moderation/yes/', ModerYesView.as_view(), name='moder_choose_yes'),
    path('adds/<int:pk>/moderation/no/', ModerNoView.as_view(), name='moder_choose_no'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
STATUS_CHOICES = [('for_moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('for_delete', 'На удаление')]
# Create your models here.


class Category(models.Model):
    categoryname = models.CharField(max_length=150, null=False, blank=False, verbose_name="Категория")

    def __str__(self):
        return f'{self.categoryname}'
class Ads(models.Model):
    picture = models.ImageField(null=True, blank=True, upload_to='picture', verbose_name='Картинка')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name='Заголовок')
    description = models.TextField(max_length=2000, verbose_name='Описание', null=True, blank=True)
    ads_author = models.ForeignKey(get_user_model(), related_name='author' , on_delete=models.CASCADE, verbose_name='Автор')
    category = models.ForeignKey('webapp.Category', related_name='category', on_delete=models.PROTECT, verbose_name="Категория")
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name='Цена')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0],
                                verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления')


    class Meta:
        permissions = [("view_not_moderated_ads", "Просмотр непромодерированных объявлений")]
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    ad = models.ForeignKey('webapp.Ads', related_name='comment', on_delete=models.CASCADE,
                                verbose_name='Комментарий')
    text = models.TextField(max_length=2000, verbose_name='Текст', null=False, blank=False)
    comment_author = models.ForeignKey(get_user_model(), related_name='comment_author', on_delete=models.CASCADE,
                               verbose_name='Автор', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

source/webapp/forms.py
from django import forms
from webapp.models import Ads , Comment

class AdsForm(forms.ModelForm):
    class Meta:
        model = Ads
        fields = ["title", "description", "category", "picture", "price"]



class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

source/webapp/views/ads_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Ads
from webapp.forms import AdsForm , CommentsForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
class AdsList(ListView):
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    model = Ads
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(status='published').order_by('-created_at')

class AdDetail(DetailView):
    template_name = 'ads/ads_detail.html'
    context_object_name = 'ad'
    model = Ads

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment = self.object.comment.all()
        # if not self.request.user.has_perm('webapp.view_not_moderated_reviews'):
        #     reviews = reviews.filter(moderated=True)
        context['form'] = CommentsForm
        context['comments'] = comment.order_by('-created_at')
        return  context

class AdsCreate(LoginRequiredMixin, CreateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_create.html'

    def form_valid(self, form):
        author = self.request.user
        form.instance.ads_author = author
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsUpdate(PermissionRequiredMixin, UpdateView):
    form_class = AdsForm
    model = Ads
    template_name = 'ads/ad_update.html'

    def get(self, request, *args, **kwargs):
        ad =  get_object_or_404(Ads, pk = self.kwargs.get('pk'))
        if ad.status == 'rejected':
            raise PermissionDenied()
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.status = 'for_moderation'
        return super().form_valid(form)

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.pk})

class AdsDelete(PermissionRequiredMixin, DeleteView):
    model = Ads
    template_name = 'ads/ad_delete.html'
    permission_required = 'webapp.delete_review'
    context_object_name = 'ad'

    def has_permission(self):
        return self.get_object().ads_author == self.request.user

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = 'for_delete'
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse('webapp:index')

class ListMooderateComments(PermissionRequiredMixin, ListView):
    model = Ads
    template_name = 'ads/moderate_list.html'
    context_object_name = 'ads'
    permission_required = 'webapp.view_not_moderated_ads'

    def get_queryset(self):
        return super().get_queryset().filter(status='for_moderation')

class ModerYesView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'published'
        ads.save()
        response = JsonResponse({})
        return response

class ModerNoView(View):
    def get(self, request, *args, **kwargs):
        ads = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        ads.status = 'rejected'
        ads.save()
        response = JsonResponse({})
        return response

source/webapp/views/comment_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView
from webapp.forms import CommentsForm
from webapp.models import Comment , Ads
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin



class CommentDelete(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk})

class CommentsCreate(CreateView):
    model = Comment
    form_class = CommentsForm

    def form_valid(self, form):
        ad = get_object_or_404(Ads, pk=self.kwargs.get('pk'))
        form.instance.comment_author = self.request.user
        form.instance.ad = ad
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ad_detail', kwargs={'pk': self.object.ad.pk} )

source/webapp/templates/ads/ad_create.html
{% extends 'base.html' %}

{% block nav %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Создание Обьявления</h1>
    <form action="" method="POST" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Создать' %}
    </form>
{% endblock %}

source/webapp/templates/ads/ad_delete.html
{% extends "base.html" %}

{% block title %}Delete Issue{% endblock %}
{% block nav %}
{% endblock %}
{% block content %}
    <h1 class="text-center mt-5">Are you sure want to delete ad "{{ ad.title }}"?</h1>
    <form method="POST"  class="text-center">
        {% csrf_token %}
        <p class="mt-5"><input type="submit" value="Confirm" class="btn btn-dark"></p>
        <p><a class="btn btn-secondary" href="{% url 'webapp:ad_detail' ad.pk %}">Cancel</a></p>
    </form>

{% endblock %}

source/webapp/templates/ads/ad_update.html
{% extends 'base.html' %}

{% block nav %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Обновление Обьявления</h1>
    <form action="" method="POST" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='Обновить' %}
    </form>
{% endblock %}

source/webapp/templates/ads/ads_detail.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}




{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        {%  if ad.picture %}
            <img src="{{ ad.picture.url }}" class="card-img-top" alt="...">
        {% else %}
            <img src="{% static "images/empty.jpg" %}" class="card-img-top">
        {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ ad.title }}</h5>
            <p>Описание: {{ ad.description }}</p>
            <p>Категория: {{ ad.category }}</p>
            <p>Цена: {{ ad.price }}</p>
            <p>Статус: {{ ad.get_status_display }}</p>
            <p>Автор:<a href="{% url 'accounts:user_detail' ad.ads_author.pk %}">{{ ad.ads_author }}</a></p>
            {% if ad.ads_author == request.user %}
              {% if ad.status != 'rejected' %}
            <a href="{% url 'webapp:ad_update' ad.pk %}" class="btn btn-primary">Update</a>
              {% endif %}
            <a href="{% url 'webapp:ad_delete' ad.pk %}" class="btn btn-primary">Delete</a>

            {% endif %}

          </div>
        </div>

    <hr>
{% if request.user.is_authenticated %}
    {% if ad.ads_author != request.user %}
      <form action="{% url 'webapp:comments_create' ad.pk %}" method="POST">
        {% include 'partial/form.html' with button_text='Оставить отзыв' %}
    </form>
    {% endif %}
{% endif %}

   {%  include 'partial/comments.html' %}

{% endblock %}

source/webapp/templates/ads/index.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}

{% endblock %}


{% block content %}
    {% for ad in ads %}
        <div class="card" style="width: 18rem;">
        {%  if ad.picture %}
            <img src="{{ ad.picture.url }}" class="card-img-top" alt="...">
        {% else %}
            <img src="{% static "images/empty.jpg" %}" class="card-img-top">
        {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ ad.title }}</h5>
              <p>{{ ad.price }}</p>
              <p>{{ad.get_status_display }}</p>
            <a href="{% url 'webapp:ad_detail' ad.pk %}" class="btn btn-primary">More...</a>
           {% if ad.ads_author == request.user %}
           <a href="{% url 'webapp:ad_update' ad.pk %}" class="btn btn-primary">Update</a>
          <a href="{% url 'webapp:ad_delete' ad.pk %}" class="btn btn-primary">Delete</a>
              {% endif %}
          </div>
        </div>
        </br>
    {% endfor %}

{% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}
{% endblock %}

source/webapp/templates/ads/moderate_list.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}

{% endblock %}


{% block content %}
{% for ad in ads %}
<div id="div_{{ ad.pk }}" >
<div class="card" style="width: 18rem;" >
    {% if ad.picture %}
    <img src="{{ ad.picture.url }}" class="card-img-top" alt="...">
    {% else %}
    <img src="{% static '/images/empty.jpg' %}" class="card-img-top">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ ad.title }}</h5>
        <p>{{ ad.price }}</p>
        <p>{{ad.get_status_display }}</p>
        <button href="#" data-pk="{{ ad.pk }}" onclick="buttonClick(event)"
                data-link="{% url 'webapp:moder_choose_yes' ad.pk %}" class="btn btn-success">Одобрить</button>
        <a href="#" data-pk="{{ ad.pk }}" onclick="buttonClick(event)" data-link="{% url 'webapp:moder_choose_no' ad.pk %}"
           class="btn btn-danger">Отклонить</a>

    </div>
</div>
    </div>
</br>
{% endfor %}

    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}